proxy-groups:
  - name: é€‰æ‹©ä»£ç†
    icon: https://gcore.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - ä½å€ç‡èŠ‚ç‚¹
      - æ‰‹åŠ¨é€‰æ‹©
      - DIRECT
  - name: æ‰‹åŠ¨é€‰æ‹©
    icon: https://gcore.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: AI
    icon: https://gcore.jsdelivr.net/gh/powerfullz/override-rules@master/icons/chatgpt.png
    type: select
    proxies: &a1
      - é€‰æ‹©ä»£ç†
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - ä½å€ç‡èŠ‚ç‚¹
      - æ‰‹åŠ¨é€‰æ‹©
      - DIRECT
  - name: Crypto
    icon: https://gcore.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cryptocurrency_3.png
    type: select
    proxies: *a1
  - name: ä½å€ç‡èŠ‚ç‚¹
    icon: https://gcore.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Lab.png
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    include-all: true
    filter: (?i)0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
  - name: é¦™æ¸¯èŠ‚ç‚¹
    icon: https://gcore.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: é¦™æ¸¯|æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|ğŸ‡­ğŸ‡°
    exclude-filter: 0\.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: select
    url: https://cp.cloudflare.com/generate_204
    interval: 30
    tolerance: 20
    lazy: false
  - name: å°æ¹¾èŠ‚ç‚¹
    icon: https://gcore.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|ğŸ‡¹ğŸ‡¼
    exclude-filter: 0\.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: select
    url: https://cp.cloudflare.com/generate_204
    interval: 30
    tolerance: 20
    lazy: false
  - name: æ–°åŠ å¡èŠ‚ç‚¹
    icon: https://gcore.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|ğŸ‡¸ğŸ‡¬
    exclude-filter: 0\.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: select
    url: https://cp.cloudflare.com/generate_204
    interval: 30
    tolerance: 20
    lazy: false
  - name: æ—¥æœ¬èŠ‚ç‚¹
    icon: https://gcore.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan|ğŸ‡¯ğŸ‡µ
    exclude-filter: 0\.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: select
    url: https://cp.cloudflare.com/generate_204
    interval: 30
    tolerance: 20
    lazy: false
  - name: ç¾å›½èŠ‚ç‚¹
    icon: https://gcore.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: ç¾å›½|ç¾|US|United States|ğŸ‡ºğŸ‡¸
    exclude-filter: 0\.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: select
    url: https://cp.cloudflare.com/generate_204
    interval: 30
    tolerance: 20
    lazy: false
  - name: GLOBAL
    icon: https://gcore.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    type: select
    proxies:
      - é€‰æ‹©ä»£ç†
      - æ‰‹åŠ¨é€‰æ‹©
      - AI
      - Crypto
      - ä½å€ç‡èŠ‚ç‚¹
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
rule-providers:
  ADBlock:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://adrules.top/adrules-mihomo.mrs
    path: ./ruleset/ADBlock.mrs
  SogouInput:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt
    path: ./ruleset/SogouInput.txt
  StaticResources:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./ruleset/StaticResources.txt
  CDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./ruleset/CDNResources.txt
  TikTok:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://gcore.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/TikTok.list
    path: ./ruleset/TikTok.list
  EHentai:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://gcore.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/EHentai.list
    path: ./ruleset/EHentai.list
  SteamFix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://gcore.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/SteamFix.list
    path: ./ruleset/SteamFix.list
  GoogleFCM:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://gcore.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list
    path: ./ruleset/FirebaseCloudMessaging.list
  AdditionalFilter:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://gcore.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalFilter.list
    path: ./ruleset/AdditionalFilter.list
  AdditionalCDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://gcore.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalCDNResources.list
    path: ./ruleset/AdditionalCDNResources.list
  Crypto:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://gcore.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/Crypto.list
    path: ./ruleset/Crypto.list
rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),REJECT
  - RULE-SET,ADBlock,REJECT
  - RULE-SET,AdditionalFilter,REJECT
  - RULE-SET,SogouInput,REJECT
  - RULE-SET,Crypto,Crypto
  - GEOSITE,CATEGORY-AI-!CN,AI
  - RULE-SET,StaticResources,DIRECT
  - RULE-SET,CDNResources,DIRECT
  - RULE-SET,AdditionalCDNResources,DIRECT
  - RULE-SET,SteamFix,DIRECT
  - RULE-SET,GoogleFCM,DIRECT
  - GEOSITE,GOOGLE-PLAY@CN,DIRECT
  - GEOSITE,MICROSOFT@CN,DIRECT
  - GEOSITE,BILIBILI,DIRECT
  - DOMAIN,services.googleapis.cn,é€‰æ‹©ä»£ç†
  - DOMAIN-SUFFIX,truthsocial.com,é€‰æ‹©ä»£ç†
  - RULE-SET,EHentai,é€‰æ‹©ä»£ç†
  - RULE-SET,TikTok,é€‰æ‹©ä»£ç†
  - GEOSITE,ONEDRIVE,é€‰æ‹©ä»£ç†
  - GEOSITE,MICROSOFT,é€‰æ‹©ä»£ç†
  - GEOSITE,TELEGRAM,é€‰æ‹©ä»£ç†
  - GEOSITE,YOUTUBE,é€‰æ‹©ä»£ç†
  - GEOSITE,GOOGLE,é€‰æ‹©ä»£ç†
  - GEOSITE,NETFLIX,é€‰æ‹©ä»£ç†
  - GEOSITE,SPOTIFY,é€‰æ‹©ä»£ç†
  - GEOSITE,BAHAMUT,é€‰æ‹©ä»£ç†
  - GEOSITE,PIKPAK,é€‰æ‹©ä»£ç†
  - GEOSITE,GFW,é€‰æ‹©ä»£ç†
  - GEOSITE,CN,DIRECT
  - GEOSITE,PRIVATE,DIRECT
  - GEOIP,CN,DIRECT
  - GEOIP,PRIVATE,DIRECT
  - MATCH,é€‰æ‹©ä»£ç†
sniffer:
  sniff:
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080
        - 8880
    QUIC:
      ports:
        - 443
        - 8443
  override-destination: false
  enable: true
  force-dns-mapping: true
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.push.apple.com
dns:
  enable: true
  ipv6: false
  prefer-h3: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - system
    - 223.5.5.5
    - 119.29.29.29
    - 180.184.1.1
  fallback:
    - quic://dns0.eu
    - https://dns.cloudflare.com/dns-query
    - https://dns.sb/dns-query
    - tcp://208.67.222.222
    - tcp://8.26.56.2
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - tls://dot.pub
  fake-ip-filter:
    - geosite:private
    - geosite:connectivity-check
    - geosite:cn
    - Mijia Cloud
    - dig.io.mi.com
    - localhost.ptlogin2.qq.com
    - "*.icloud.com"
    - "*.stun.*.*"
    - "*.stun.*.*.*"
geodata-mode: true
geox-url:
  geoip: https://gcore.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://gcore.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://gcore.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
  asn: https://gcore.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb

